version: '3'
services:
  frontend:
    container_name: Front-React-TS
    restart: always
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    command: "./start_dev.sh"
    ports:
      - '3000:3000'
    volumes:
      - "./frontend:/usr/src/app"

  backend:
    container_name: API-Container
    restart: always
    build: 
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    command: "./start_dev.sh"
    ports:
      - '3001:3000'
    volumes:
      - "./backend:/usr/src/app"
    environment:
      - MONGO_USER=dev
      - MONGO_PASSWORD=stage
      - MONGO_HOST=mongodb://mongo:27017
      - MONGO_DATABASE=Stage
      - PORT=3000
      - USER_PASSWORD=pass
      - JWT_SECRET=stagePass
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: stage