version: '3'
services:
  backend:
    container_name: API-Container
    restart: always
    build: 
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    command: "./start_dev.sh"
    ports:
      - '3000:3000'
    volumes:
      - "./backend:/usr/src/app"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: stage